import type { Round } from "@/types/game";

// Generated by the password-protected moment import tool.
// Approved imported rounds are written here so they become part of the app.
export const importedRounds: Round[] = [
  {
    "id": "1980-miracle-on-ice-2",
    "title": "Miracle on Ice",
    "imageUrl": "/rounds/1980-miracle-on-ice-2.png",
    "actualYear": 1980,
    "actualLocation": {
      "name": "Olympic Fieldhouse",
      "city": "Lake Placid, New York",
      "country": "United States",
      "lat": 44.2796,
      "lng": -73.9799
    },
    "description": "The underdog United States hockey team shocked the heavily favored Soviet Union during the 1980 Winter Olympics in one of the greatest upsets in sports history."
  }
];
