import type { Round } from "@/types/game";

// Generated by the password-protected moment import tool.
// Approved imported rounds are written here so they become part of the app.
export const importedRounds: Round[] = [
  {
    "id": "1980-miracle-on-ice-2",
    "title": "Miracle on Ice",
    "imageUrl": "/rounds/1980-miracle-on-ice-2.png",
    "level": "Medium",
    "actualYear": 1980,
    "actualMonth": "February",
    "actualDay": 22,
    "actualLocation": {
      "name": "Olympic Fieldhouse",
      "city": "Lake Placid, New York",
      "country": "United States",
      "lat": 44.2796,
      "lng": -73.9799
    },
    "description": "The underdog United States hockey team shocked the heavily favored Soviet Union during the 1980 Winter Olympics in one of the greatest upsets in sports history."
  },
  {
    "id": "1973-secretariat-belmont-stakes-dominance",
    "title": "Secretariat — Belmont Stakes Dominance",
    "imageUrl": "/rounds/1973-secretariat-belmont-stakes-dominance.png",
    "level": "Hard",
    "actualYear": 1973,
    "actualMonth": "June",
    "actualDay": 9,
    "actualLocation": {
      "name": "Belmont Park",
      "city": "Elmont, New York",
      "country": "United States",
      "lat": 40.7156,
      "lng": -73.7214
    },
    "description": "Secretariat delivered one of the greatest performances in sports history by winning the 1973 Belmont Stakes by 31 lengths and securing the Triple Crown in record-setting fashion."
  },
  {
    "id": "1965-the-phantom-punch",
    "title": "The Phantom Punch",
    "imageUrl": "/rounds/1965-the-phantom-punch.png",
    "level": "Medium",
    "actualYear": 1965,
    "actualMonth": "May",
    "actualDay": 25,
    "actualLocation": {
      "name": "Central Maine Youth Center",
      "city": "Lewiston, Maine",
      "country": "United States",
      "lat": 44.1004,
      "lng": -70.2197
    },
    "description": "Muhammad Ali knocked out Sonny Liston in the first round and stood triumphantly over him in one of the most iconic moments in boxing history."
  },
  {
    "id": "1954-willie-mays-the-catch",
    "title": "Willie Mays — The Catch",
    "imageUrl": "/rounds/1954-willie-mays-the-catch.png",
    "level": "Medium",
    "actualYear": 1954,
    "actualMonth": "September",
    "actualDay": 29,
    "actualLocation": {
      "name": "Polo Grounds",
      "city": "New York, New York",
      "country": "United States",
      "lat": 40.8309,
      "lng": -73.9365
    },
    "description": "Willie Mays made his legendary over-the-shoulder catch in deep center field during Game 1 of the 1954 World Series."
  },
  {
    "id": "2016-lebron-james-the-block",
    "title": "LeBron James — The Block",
    "imageUrl": "/rounds/2016-lebron-james-the-block.png",
    "level": "Easy",
    "actualYear": 2016,
    "actualMonth": "June",
    "actualDay": 19,
    "actualLocation": {
      "name": "Oracle Arena",
      "city": "Oakland, California",
      "country": "United States",
      "lat": 37.7503,
      "lng": -122.203
    },
    "description": "LeBron James delivered a historic chase-down block on Andre Iguodala in Game 7 of the 2016 NBA Finals, helping Cleveland complete a comeback from a 3–1 series deficit."
  },
  {
    "id": "2018-cristiano-ronaldo-bicycle-kick",
    "title": "Cristiano Ronaldo — Bicycle Kick",
    "imageUrl": "/rounds/2018-cristiano-ronaldo-bicycle-kick.png",
    "level": "Hard",
    "actualYear": 2018,
    "actualMonth": "April",
    "actualDay": 3,
    "actualLocation": {
      "name": "Allianz Stadium",
      "city": "Turin",
      "country": "Italy",
      "lat": 45.1096,
      "lng": 7.6413
    },
    "description": "Cristiano Ronaldo scored a spectacular bicycle kick for Real Madrid against Juventus during the UEFA Champions League quarterfinals, earning applause from opposing fans."
  },
  {
    "id": "1982-dwight-clark-the-catch",
    "title": "Dwight Clark — “The Catch”",
    "imageUrl": "/rounds/1982-dwight-clark-the-catch.png",
    "level": "Hard",
    "actualYear": 1982,
    "actualMonth": "January",
    "actualDay": 10,
    "actualLocation": {
      "name": "Candlestick Park",
      "city": "San Francisco, California",
      "country": "United States",
      "lat": 37.7135,
      "lng": -122.3866
    },
    "description": "Dwight Clark made the iconic leaping touchdown catch from Joe Montana in the closing moments of the 1981 NFC Championship Game, sending the San Francisco 49ers to their first Super Bowl."
  },
  {
    "id": "2006-zinedine-zidane-a-stunning-final-exit",
    "title": "Zinedine Zidane — A Stunning Final Exit",
    "imageUrl": "/rounds/2006-zinedine-zidane-a-stunning-final-exit.png",
    "level": "Hard",
    "actualYear": 2006,
    "actualMonth": "July",
    "actualDay": 9,
    "actualLocation": {
      "name": "Olympiastadion Berlin",
      "city": "Berlin",
      "country": "Germany",
      "lat": 52.5147,
      "lng": 13.2394
    },
    "description": "In the final match of his legendary career, Zinedine Zidane was sent off after headbutting Marco Materazzi during extra time of the 2006 FIFA World Cup Final."
  },
  {
    "id": "2010-andr-s-iniesta-spain-s-historic-triumph",
    "title": "Andrés Iniesta — Spain’s Historic Triumph",
    "imageUrl": "/rounds/2010-andr-s-iniesta-spain-s-historic-triumph.png",
    "level": "Medium",
    "actualYear": 2010,
    "actualMonth": "July",
    "actualDay": 11,
    "actualLocation": {
      "name": "Soccer City Stadium",
      "city": "Johannesburg",
      "country": "South Africa",
      "lat": -26.2347,
      "lng": 27.9826
    },
    "description": "Andrés Iniesta scored the extra-time winner against the Netherlands to give Spain its first FIFA World Cup title in 2010."
  },
  {
    "id": "1993-joe-carter-touch-em-all-joe",
    "title": "Joe Carter — “Touch ’Em All Joe”",
    "imageUrl": "/rounds/1993-joe-carter-touch-em-all-joe.png",
    "level": "Hard",
    "actualYear": 1993,
    "actualMonth": "October",
    "actualDay": 23,
    "actualLocation": {
      "name": "SkyDome",
      "city": "Toronto, Ontario",
      "country": "Canada",
      "lat": 43.6414,
      "lng": -79.3894
    },
    "description": "Joe Carter hit a walk-off three-run home run in Game 6 of the 1993 World Series, clinching a second straight championship for the Toronto Blue Jays."
  },
  {
    "id": "2013-ray-allen-saving-the-heat-dynasty",
    "title": "Ray Allen — Saving the Heat Dynasty",
    "imageUrl": "/rounds/2013-ray-allen-saving-the-heat-dynasty.png",
    "level": "Medium",
    "actualYear": 2013,
    "actualMonth": "June",
    "actualDay": 18,
    "actualLocation": {
      "name": "American Airlines Arena",
      "city": "Miami, Florida",
      "country": "United States",
      "lat": 25.7814,
      "lng": -80.187
    },
    "description": "Ray Allen hit a legendary game-tying corner three-pointer in the closing seconds of Game 6 of the 2013 NBA Finals, helping the Miami Heat force overtime and eventually win the championship."
  },
  {
    "id": "1992-christian-laettner-the-shot",
    "title": "Christian Laettner — The Shot",
    "imageUrl": "/rounds/1992-christian-laettner-the-shot.png",
    "level": "Hard",
    "actualYear": 1992,
    "actualMonth": "March",
    "actualDay": 28,
    "actualLocation": {
      "name": "Spectrum",
      "city": "Philadelphia, Pennsylvania",
      "country": "United States",
      "lat": 39.901,
      "lng": -75.1719
    },
    "description": "Christian Laettner hit a perfect turnaround buzzer-beater for Duke against Kentucky in the 1992 NCAA Tournament, creating one of the most iconic moments in college basketball history."
  },
  {
    "id": "1974-hank-aaron-passing-babe-ruth",
    "title": "Hank Aaron — Passing Babe Ruth",
    "imageUrl": "/rounds/1974-hank-aaron-passing-babe-ruth.png",
    "level": "Medium",
    "actualYear": 1974,
    "actualMonth": "April",
    "actualDay": 8,
    "actualLocation": {
      "name": "Atlanta Stadium",
      "city": "Atlanta, Georgia",
      "country": "United States",
      "lat": 33.7356,
      "lng": -84.3895
    },
    "description": "Hank Aaron hit his 715th career home run to surpass Babe Ruth’s all-time record, becoming one of the most historic moments in baseball history."
  },
  {
    "id": "1986-mookie-wilson-through-buckner-s-legs",
    "title": "Mookie Wilson — Through Buckner’s Legs",
    "imageUrl": "/rounds/1986-mookie-wilson-through-buckner-s-legs.png",
    "level": "Brutal",
    "actualYear": 1986,
    "actualMonth": "October",
    "actualDay": 25,
    "actualLocation": {
      "name": "Shea Stadium",
      "city": "New York City, New York",
      "country": "United States",
      "lat": 40.7571,
      "lng": -73.8458
    },
    "description": "round ball rolled through Bill Buckner’s legs in Game 6 of the 1986 World Series, allowing the New York Mets to complete an improbable comeback and force Game 7."
  },
  {
    "id": "2001-randy-johnson-the-bird-strike",
    "title": "Randy Johnson — The Bird Strike",
    "imageUrl": "/rounds/2001-randy-johnson-the-bird-strike.png",
    "level": "Brutal",
    "actualYear": 2001,
    "actualMonth": "March",
    "actualDay": 24,
    "actualLocation": {
      "name": "Tucson Electric Park",
      "city": "Tucson, Arizona",
      "country": "United States",
      "lat": 32.1697,
      "lng": -110.9176
    },
    "description": "During a spring training game, Randy Johnson accidentally struck and killed a bird with a fastball, creating one of the strangest and most surreal moments in baseball history."
  },
  {
    "id": "2007-devin-hester-opening-shockwave",
    "title": "Devin Hester — Opening Shockwave",
    "imageUrl": "/rounds/2007-devin-hester-opening-shockwave.png",
    "level": "Medium",
    "actualYear": 2007,
    "actualMonth": "February",
    "actualDay": 4,
    "actualLocation": {
      "name": "Dolphin Stadium",
      "city": "Miami Gardens, Florida",
      "country": "United States",
      "lat": 25.958,
      "lng": -80.2389
    },
    "description": "Devin Hester returned the opening kickoff of Super Bowl XLI for a touchdown, becoming the first player in Super Bowl history to score on the opening kickoff."
  },
  {
    "id": "1991-michael-jordan-the-beginning-of-the-dynasty",
    "title": "Michael Jordan — The Beginning of the Dynasty",
    "imageUrl": "/rounds/1991-michael-jordan-the-beginning-of-the-dynasty.png",
    "level": "Medium",
    "actualYear": 1991,
    "actualMonth": "June",
    "actualDay": 12,
    "actualLocation": {
      "name": "Great Western Forum",
      "city": "Inglewood, California",
      "country": "United States",
      "lat": 33.9583,
      "lng": -118.3417
    },
    "description": "Michael Jordan captured his first NBA championship as the Chicago Bulls defeated the Los Angeles Lakers in the 1991 NBA Finals, launching one of the greatest dynasties in sports history."
  },
  {
    "id": "1999-serena-williams-first-of-many",
    "title": "Serena Williams — First of Many",
    "imageUrl": "/rounds/1999-serena-williams-first-of-many.png",
    "level": "Hard",
    "actualYear": 1999,
    "actualMonth": "September",
    "actualDay": 11,
    "actualLocation": {
      "name": "Arthur Ashe Stadium",
      "city": "New York City, New York",
      "country": "United States",
      "lat": 40.7498,
      "lng": -73.8476
    },
    "description": "At just 17 years old, Serena Williams defeated Martina Hingis to win the 1999 US Open, becoming the first African American woman in the Open Era to win a Grand Slam singles title. zoom out to get full tennies court view"
  },
  {
    "id": "2008-philadelphia-phillies-2008-world-series-champions",
    "title": "Philadelphia Phillies — 2008 World Series Champions",
    "imageUrl": "/rounds/2008-philadelphia-phillies-2008-world-series-champions.png",
    "level": "Easy",
    "actualYear": 2008,
    "actualMonth": "October",
    "actualDay": 29,
    "actualLocation": {
      "name": "Citizens Bank Park",
      "city": "Philadelphia, Pennsylvania",
      "country": "United States",
      "lat": 39.9061,
      "lng": -75.1665
    },
    "description": "The Philadelphia Phillies defeated the Tampa Bay Rays to win the 2008 World Series, securing the franchise’s first championship since 1980 behind dominant pitching and clutch hitting."
  },
  {
    "id": "2001-allen-iverson-finals-step-over",
    "title": "Allen Iverson — Finals Step Over",
    "imageUrl": "/rounds/2001-allen-iverson-finals-step-over.png",
    "level": "Easy",
    "actualYear": 2001,
    "actualMonth": "June",
    "actualDay": 6,
    "actualLocation": {
      "name": "STAPLES Center",
      "city": "Los Angeles, California",
      "country": "United States",
      "lat": 34.043,
      "lng": -118.2673
    },
    "description": "Allen Iverson stepped over Tyronn Lue after hitting a clutch shot late in Game 1 of the 2001 NBA Finals, creating one of the most iconic and defiant moments in basketball history."
  },
  {
    "id": "2006-kobe-bryant-jersey-pull-celebration",
    "title": "Kobe Bryant — Jersey Pull Celebration",
    "imageUrl": "/rounds/2006-kobe-bryant-jersey-pull-celebration.png",
    "level": "Hard",
    "actualYear": 2006,
    "actualMonth": "April",
    "actualDay": 30,
    "actualLocation": {
      "name": "STAPLES Center",
      "city": "Los Angeles, California",
      "country": "United States",
      "lat": 34.043,
      "lng": -118.2673
    },
    "description": "Kobe Bryant hit a dramatic game-tying floater and an overtime buzzer-beating fadeaway against the Phoenix Suns in Game 4 of the 2006 NBA Playoffs, followed by his iconic jersey-pull celebration."
  },
  {
    "id": "2008-florida-vs-florida-state-the-mud-bowl",
    "title": "Florida vs Florida State — The Mud Bowl",
    "imageUrl": "/rounds/2008-florida-vs-florida-state-the-mud-bowl.png",
    "level": "Hard",
    "actualYear": 2008,
    "actualMonth": "November",
    "actualDay": 29,
    "actualLocation": {
      "name": "Doak Campbell Stadium",
      "city": "Tallahassee, Florida",
      "country": "United States",
      "lat": 30.4381,
      "lng": -84.3046
    },
    "description": "During a torrential rainstorm in Tallahassee, the Florida Gators defeated the Florida State Seminoles in a rivalry game remembered for its soaked field, muddy chaos, and players sliding across the waterlogged turf."
  },
  {
    "id": "2007-peyton-manning-wins-his-first-super-bowl",
    "title": "Peyton Manning Wins His First Super Bowl",
    "imageUrl": "/rounds/2007-peyton-manning-wins-his-first-super-bowl.png",
    "level": "Easy",
    "actualYear": 2007,
    "actualMonth": "February",
    "actualDay": 4,
    "actualLocation": {
      "name": "Dolphin Stadium",
      "city": "Miami Gardens, Florida",
      "country": "United States",
      "lat": 25.958,
      "lng": -80.2389
    },
    "description": "Peyton Manning led the Indianapolis Colts to victory over the Chicago Bears in Super Bowl XLI, securing the first Super Bowl championship of his legendary NFL career."
  },
  {
    "id": "2010-lebron-james-the-decision",
    "title": "LeBron James — “The Decision”",
    "imageUrl": "/rounds/2010-lebron-james-the-decision.png",
    "level": "Easy",
    "actualYear": 2010,
    "actualMonth": "July",
    "actualDay": 8,
    "actualLocation": {
      "name": "Boys & Girls Club of Greenwich",
      "city": "Greenwich, Connecticut",
      "country": "United States",
      "lat": 41.0262,
      "lng": -73.6282
    },
    "description": "LeBron James announced live on national television that he would leave the Cleveland Cavaliers to join the Miami Heat, delivering the famous line: “I’m going to take my talents to South Beach.”"
  },
  {
    "id": "2022-antonio-brown-walks-off-the-field",
    "title": "Antonio Brown Walks Off the Field",
    "imageUrl": "/rounds/2022-antonio-brown-walks-off-the-field.png",
    "level": "Easy",
    "actualYear": 2022,
    "actualMonth": "January",
    "actualDay": 2,
    "actualLocation": {
      "name": "MetLife Stadium",
      "city": "East Rutherford, New Jersey",
      "country": "United States",
      "lat": 40.8135,
      "lng": -74.0745
    },
    "description": "Antonio Brown shocked the NFL world by removing his uniform and leaving the field mid-game during the Tampa Bay Buccaneers’ matchup against the New York Jets."
  },
  {
    "id": "2005-the-bush-push",
    "title": "The Bush Push",
    "imageUrl": "/rounds/2005-the-bush-push.png",
    "level": "Hard",
    "actualYear": 2005,
    "actualMonth": "October",
    "actualDay": 15,
    "actualLocation": {
      "name": "Notre Dame Stadium",
      "city": "Notre Dame, Indiana",
      "country": "United States",
      "lat": 41.6986,
      "lng": -86.2339
    },
    "description": "In one of college football’s most controversial endings, USC quarterback Matt Leinart scored the game-winning touchdown after Reggie Bush appeared to illegally push him into the end zone against Notre Dame."
  },
  {
    "id": "2018-jr-smith-s-finals-blunder",
    "title": "JR Smith’s Finals Blunder",
    "imageUrl": "/rounds/2018-jr-smith-s-finals-blunder.png",
    "level": "Medium",
    "actualYear": 2018,
    "actualMonth": "May",
    "actualDay": 31,
    "actualLocation": {
      "name": "Oracle Arena",
      "city": "Oakland, California",
      "country": "United States",
      "lat": 37.7503,
      "lng": -122.2029
    },
    "description": "After securing an offensive rebound in the closing seconds of Game 1 of the NBA Finals, JR Smith mistakenly dribbled away from the basket, seemingly unaware the game was tied, causing Lebron to scream at him near the score table"
  },
  {
    "id": "2018-khabib-jumps-the-cage-after-defeating-mcgregor",
    "title": "Khabib Jumps the Cage After Defeating McGregor",
    "imageUrl": "/rounds/2018-khabib-jumps-the-cage-after-defeating-mcgregor.png",
    "level": "Brutal",
    "actualYear": 2018,
    "actualMonth": "October",
    "actualDay": 6,
    "actualLocation": {
      "name": "T-Mobile Arena",
      "city": "Las Vegas, Nevada",
      "country": "United States",
      "lat": 36.1028,
      "lng": -115.1781
    },
    "description": "After submitting Conor McGregor at UFC 229 inside the cage, Khabib Nurmagomedov held back by the referee inside the cage"
  },
  {
    "id": "2018-tua-and-devonta-connect-for-the-title",
    "title": "Tua and DeVonta Connect for the Title",
    "imageUrl": "/rounds/2018-tua-and-devonta-connect-for-the-title.png",
    "level": "Easy",
    "actualYear": 2018,
    "actualMonth": "January",
    "actualDay": 8,
    "actualLocation": {
      "name": "Mercedes-Benz Stadium",
      "city": "Atlanta, Georgia",
      "country": "United States",
      "lat": 33.7554,
      "lng": -84.4009
    },
    "description": "touchdown pass to DeVonta Smith in the far left hand corner just before the endzone in overtime to defeat Georgia and win the College Football Playoff National Championship for Alabama"
  },
  {
    "id": "1999-brandi-chastain-s-iconic-celebration",
    "title": "Brandi Chastain’s Iconic Celebration",
    "imageUrl": "/rounds/1999-brandi-chastain-s-iconic-celebration.png",
    "level": "Hard",
    "actualYear": 1999,
    "actualMonth": "July",
    "actualDay": 10,
    "actualLocation": {
      "name": "Rose Bowl Stadium",
      "city": "Pasadena, California",
      "country": "United States",
      "lat": 34.1613,
      "lng": -118.1676
    },
    "description": "After scoring the winning penalty kick to give the United States the Women’s World Cup title, Brandi Chastain celebrated with one of the most iconic moments in soccer history."
  },
  {
    "id": "2008-the-helmet-catch",
    "title": "The Helmet Catch",
    "imageUrl": "/rounds/2008-the-helmet-catch.png",
    "level": "Easy",
    "actualYear": 2008,
    "actualMonth": "February",
    "actualDay": 3,
    "actualLocation": {
      "name": "University of Phoenix Stadium",
      "city": "Glendale, Arizona",
      "country": "United States",
      "lat": 33.5276,
      "lng": -112.2626
    },
    "description": "Eli Manning escaped multiple defenders before launching a desperate pass to David Tyree, who pinned the ball against his helmet for one of the greatest catches in Super Bowl history during the Giants’ upset over the Patriots."
  },
  {
    "id": "1991-magic-johnson-announces-he-has-hiv",
    "title": "Magic Johnson Announces He Has HIV",
    "imageUrl": "/rounds/1991-magic-johnson-announces-he-has-hiv.png",
    "level": "Brutal",
    "actualYear": 1991,
    "actualMonth": "November",
    "actualDay": 7,
    "actualLocation": {
      "name": "The Forum",
      "city": "Inglewood, California",
      "country": "United States",
      "lat": 33.958,
      "lng": -118.3417
    },
    "description": "Magic Johnson shocked the sports world by announcing he had tested positive for HIV, leading to his immediate retirement from the NBA and transforming public awareness around the disease. show name \"Magic Johnson\" name on front pedastal"
  },
  {
    "id": "2004-malice-at-the-palace",
    "title": "Malice at the Palace",
    "imageUrl": "/rounds/2004-malice-at-the-palace.png",
    "level": "Medium",
    "actualYear": 2004,
    "actualMonth": "November",
    "actualDay": 19,
    "actualLocation": {
      "name": "The Palace of Auburn Hills",
      "city": "Auburn Hills, Michigan",
      "country": "United States",
      "lat": 42.6969,
      "lng": -83.2455
    },
    "description": "A late-game altercation between the Indiana Pacers and Detroit Pistons escalated into a massive brawl involving players and fans, creating one of the most infamous incidents in NBA history."
  },
  {
    "id": "2003-the-steve-bartman-incident",
    "title": "The Steve Bartman Incident",
    "imageUrl": "/rounds/2003-the-steve-bartman-incident.png",
    "level": "Medium",
    "actualYear": 2003,
    "actualMonth": "October",
    "actualDay": 14,
    "actualLocation": {
      "name": "Wrigley Field",
      "city": "Chicago, Illinois",
      "country": "United States",
      "lat": 41.9484,
      "lng": -87.6553
    },
    "description": "Cubs fan Steve Bartman unintentionally interfered with a foul ball during Game 6 of the NLCS, becoming one of the most infamous moments in baseball history as Chicago’s collapse continued."
  },
  {
    "id": "2008-cristiano-ronaldo-wins-his-first-ballon-d-or",
    "title": "Cristiano Ronaldo Wins His First Ballon d’Or",
    "imageUrl": "/rounds/2008-cristiano-ronaldo-wins-his-first-ballon-d-or.png",
    "level": "Brutal",
    "actualYear": 2008,
    "actualMonth": "December",
    "actualDay": 2,
    "actualLocation": {
      "name": "Pavillon d'Armenonville",
      "city": "Paris",
      "country": "France",
      "lat": 48.879,
      "lng": 2.2645
    },
    "description": "Cristiano Ronaldo captured the first Ballon d’Or of his career after a spectacular season with Manchester United, beginning an era of global dominance alongside Lionel Messi."
  },
  {
    "id": "2015-jos-bautista-s-iconic-bat-flip",
    "title": "José Bautista’s Iconic Bat Flip",
    "imageUrl": "/rounds/2015-jos-bautista-s-iconic-bat-flip.png",
    "level": "Medium",
    "actualYear": 2015,
    "actualMonth": "October",
    "actualDay": 14,
    "actualLocation": {
      "name": "Rogers Centre",
      "city": "Toronto, Ontario",
      "country": "Canada",
      "lat": 43.6414,
      "lng": -79.3894
    },
    "description": "José Bautista launched a dramatic three-run homer against the Texas Rangers and unleashed an unforgettable bat flip that became one of baseball’s defining postseason celebrations."
  }
];
