import type { Round } from "@/types/game";

// Generated by the password-protected moment import tool.
// Approved imported rounds are written here so they become part of the app.
export const importedRounds: Round[] = [
  {
    "id": "1980-miracle-on-ice-2",
    "title": "Miracle on Ice",
    "imageUrl": "/rounds/1980-miracle-on-ice-2.png",
    "actualYear": 1980,
    "actualMonth": "February",
    "actualDay": 22,
    "actualLocation": {
      "name": "Olympic Fieldhouse",
      "city": "Lake Placid, New York",
      "country": "United States",
      "lat": 44.2796,
      "lng": -73.9799
    },
    "description": "The underdog United States hockey team shocked the heavily favored Soviet Union during the 1980 Winter Olympics in one of the greatest upsets in sports history."
  },
  {
    "id": "1973-secretariat-belmont-stakes-dominance",
    "title": "Secretariat — Belmont Stakes Dominance",
    "imageUrl": "/rounds/1973-secretariat-belmont-stakes-dominance.png",
    "actualYear": 1973,
    "actualMonth": "June",
    "actualDay": 9,
    "actualLocation": {
      "name": "Belmont Park",
      "city": "Elmont, New York",
      "country": "United States",
      "lat": 40.7156,
      "lng": -73.7214
    },
    "description": "Secretariat delivered one of the greatest performances in sports history by winning the 1973 Belmont Stakes by 31 lengths and securing the Triple Crown in record-setting fashion."
  },
  {
    "id": "1965-the-phantom-punch",
    "title": "The Phantom Punch",
    "imageUrl": "/rounds/1965-the-phantom-punch.png",
    "actualYear": 1965,
    "actualMonth": "May",
    "actualDay": 25,
    "actualLocation": {
      "name": "Central Maine Youth Center",
      "city": "Lewiston, Maine",
      "country": "United States",
      "lat": 44.1004,
      "lng": -70.2197
    },
    "description": "Muhammad Ali knocked out Sonny Liston in the first round and stood triumphantly over him in one of the most iconic moments in boxing history."
  },
  {
    "id": "1954-willie-mays-the-catch",
    "title": "Willie Mays — The Catch",
    "imageUrl": "/rounds/1954-willie-mays-the-catch.png",
    "actualYear": 1954,
    "actualMonth": "September",
    "actualDay": 29,
    "actualLocation": {
      "name": "Polo Grounds",
      "city": "New York, New York",
      "country": "United States",
      "lat": 40.8309,
      "lng": -73.9365
    },
    "description": "Willie Mays made his legendary over-the-shoulder catch in deep center field during Game 1 of the 1954 World Series."
  },
  {
    "id": "2016-lebron-james-the-block",
    "title": "LeBron James — The Block",
    "imageUrl": "/rounds/2016-lebron-james-the-block.png",
    "actualYear": 2016,
    "actualMonth": "June",
    "actualDay": 19,
    "actualLocation": {
      "name": "Oracle Arena",
      "city": "Oakland, California",
      "country": "United States",
      "lat": 37.7503,
      "lng": -122.203
    },
    "description": "LeBron James delivered a historic chase-down block on Andre Iguodala in Game 7 of the 2016 NBA Finals, helping Cleveland complete a comeback from a 3–1 series deficit."
  },
  {
    "id": "2018-cristiano-ronaldo-bicycle-kick",
    "title": "Cristiano Ronaldo — Bicycle Kick",
    "imageUrl": "/rounds/2018-cristiano-ronaldo-bicycle-kick.png",
    "actualYear": 2018,
    "actualMonth": "April",
    "actualDay": 3,
    "actualLocation": {
      "name": "Allianz Stadium",
      "city": "Turin",
      "country": "Italy",
      "lat": 45.1096,
      "lng": 7.6413
    },
    "description": "Cristiano Ronaldo scored a spectacular bicycle kick for Real Madrid against Juventus during the UEFA Champions League quarterfinals, earning applause from opposing fans."
  },
  {
    "id": "1982-dwight-clark-the-catch",
    "title": "Dwight Clark — “The Catch”",
    "imageUrl": "/rounds/1982-dwight-clark-the-catch.png",
    "actualYear": 1982,
    "actualMonth": "January",
    "actualDay": 10,
    "actualLocation": {
      "name": "Candlestick Park",
      "city": "San Francisco, California",
      "country": "United States",
      "lat": 37.7135,
      "lng": -122.3866
    },
    "description": "Dwight Clark made the iconic leaping touchdown catch from Joe Montana in the closing moments of the 1981 NFC Championship Game, sending the San Francisco 49ers to their first Super Bowl."
  }
];
